name: flutter_paisa
description: A expense manager app for Android & iOS by Bridge Security.

# Run these commands to run & build the app (Android):
# flutter clean
# flutter pub get
# flutter build apk --no-tree-shake-icons

publish_to: "none"

version: 2.0.2+25

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  animations: ^2.0.7
  chart_sparkline: ^1.0.8

  csv: ^5.0.1
  date_picker_timeline: ^1.2.3
  device_info_plus:
  dynamic_color: ^1.1.2
  equatable: ^2.0.3
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_charts: ^0.5.2
  flutter_local_notifications: ^11.0.1
  flutter_localization: ^0.1.14
  flutter_native_timezone: ^2.0.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^5.0.1
  google_fonts: ^4.0.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+4
  intl: ^0.18.1
  material_color_utilities:
  material_design_icons_flutter: ^5.0.6595
  package_info_plus: any
  path_provider: ^2.0.8
  permission_handler: ^10.0.1
  responsive_builder: ^0.4.1
  share_plus: ^4.0.3
  url_launcher: ^6.0.18
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.7
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter_app_name:
  name: "Time Security Systems"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/icon_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon_dark.png
    icon_background_color_dark: "#121212"

flutter_icons:
  image_path: "assets/images/icon.png"
  ios: true
  android: true
  web: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
